# Prefer system packages.

find_package(Eigen3 QUIET)
if(NOT Eigen3_FOUND)
    find_path(EIGEN3_INCLUDE_DIR Eigen/Dense PATHS /usr/include/eigen3 /usr/local/include/eigen3)
    if(EIGEN3_INCLUDE_DIR)
        add_library(Eigen3::Eigen INTERFACE IMPORTED)
        target_include_directories(Eigen3::Eigen INTERFACE ${EIGEN3_INCLUDE_DIR})
        set(Eigen3_FOUND TRUE)
    endif()
endif()

find_package(nlohmann_json QUIET)
if(NOT nlohmann_json_FOUND)
    find_path(NLOHMANN_JSON_INCLUDE nlohmann/json.hpp PATHS /usr/include)
    if(NLOHMANN_JSON_INCLUDE)
        add_library(nlohmann_json::nlohmann_json INTERFACE IMPORTED)
        target_include_directories(nlohmann_json::nlohmann_json INTERFACE ${NLOHMANN_JSON_INCLUDE})
        set(nlohmann_json_FOUND TRUE)
    endif()
endif()

find_package(yaml-cpp QUIET)
find_package(spdlog QUIET)
find_package(fmt QUIET)

if(RESILIENCE_BUILD_TESTS)
    find_package(Catch2 3 QUIET)
    if(NOT Catch2_FOUND)
        find_package(Catch2 QUIET)
    endif()
endif()

find_path(CLI11_INCLUDE_DIR CLI/CLI.hpp PATHS /usr/include /usr/local/include)
if(CLI11_INCLUDE_DIR)
    add_library(CLI11::CLI11 INTERFACE IMPORTED)
    target_include_directories(CLI11::CLI11 INTERFACE ${CLI11_INCLUDE_DIR})
    set(CLI11_FOUND TRUE)
else()
    set(CLI11_FOUND FALSE)
endif()

message(STATUS "Eigen3: ${Eigen3_FOUND}")
message(STATUS "nlohmann_json: ${nlohmann_json_FOUND}")
message(STATUS "yaml-cpp found: ${yaml-cpp_FOUND}")
message(STATUS "spdlog found: ${spdlog_FOUND}")
message(STATUS "Catch2: ${Catch2_FOUND}")
message(STATUS "CLI11: ${CLI11_FOUND}")
